# Detect if the compiler is either clang or clang++
if (CMAKE_CXX_COMPILER MATCHES ".*clang[+][+]" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  set (CMAKE_COMPILER_IS_CLANGXX 1)
endif ()

# Set the output directories
set (CMAKE_RUNTIME_OUTPUT_DIRECTORY "${BIN_OUTPUT_DIR}")
set (CMAKE_LIBRARY_OUTPUT_DIRECTORY "${DYNAMIC_LIBRARY_OUTPUT_DIR}")
set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${STATIC_LIBRARY_OUTPUT_DIR}")

# Compilation flags
if (CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANGXX)
  # g++ / clang++
  set (CMAKE_CXX_FLAGS "${GCC_COMMON_COMPILATION_FLAGS}")
  set (CMAKE_CXX_FLAGS_DEBUG "${GCC_DEBUG_COMPILATION_FLAGS}")
  set (CMAKE_CXX_FLAGS_RELEASE "${GCC_RELEASE_COMPILATION_FLAGS}")
elseif (MSVC)
  # MS Visual Studio
  set (CMAKE_CXX_FLAGS "${MSVC_COMMON_COMPILATION_FLAGS}")
  set (CMAKE_CXX_FLAGS_DEBUG "${MSVC_DEBUG_COMPILATION_FLAGS}")
  set (CMAKE_CXX_FLAGS_RELEASE "${MSVC_RELEASE_COMPILATION_FLAGS}")
endif ()
